language: ruby

rvm:
 - "2.3.0"

services:
 - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - be rake db:create
  - be rake db:migrate
  - be rake db:seed
  - be rake
