language: ruby

rvm:
 - "2.3.0"

services:
 - postgresql

before_script:
 - psql -c 'create database Mastercraft_Lighting_test;' -U postgres

script:
 - bundle exec db:create
 - bundle exec db:migrate
