# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4128394efd6481e06e9779ba2b8294d6eff80b7b2b4081d1ea8df5c19a32955c2f79660eb963c62b7c425eea15013fc9e4df2b287b6d927d5ca57744f52d4427

test:
  secret_key_base: 0ac58ff7f3bc2596db3a7609c9824f3cb8f3e387ed1bbd7aa6b2b467134e2b52331022e0aae241748acffc62d99b1fc85c767e9ce874efd9e63fac65822da3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
